# Etapa base: imagen ligera para ejecutar la app
FROM mcr.microsoft.com/dotnet/aspnet:9.0-alpine AS base
WORKDIR /app

# Etapa build: compilar y publicar la app
FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS build
WORKDIR /src

# Copiar el contenido al contenedor y restaurar dependencias
COPY . .
RUN dotnet restore

# Publicar la app en modo Release
RUN dotnet publish -c Release -o /app

# Etapa final: usar solo los archivos publicados
FROM base AS final
WORKDIR /app
COPY --from=build /app ./

# Establecer el punto de entrada
ENTRYPOINT ["dotnet", "HelloApp.dll"]
